### PR TITLE
Adds Table of Contents structure & logo

### PR DESCRIPTION
**Pull request by tippenein**
Adds a TOC linking to comments, imports, modules, hello world and operators.

The logo SVG is added as well (misaligned at the moment)

The "hello world" example uses Smolder html. It might be good to add some other options to this?

### CODE REVIEW

**Comment by joshburgess** [comment]
Do you think maybe we should show a more basic hello world? Like the one the "hello sailor" sample when you init a new project with pulp?

Also, I think our operators section will need to have more than just that one table. I think there will need to be a few tables. That one there right now only contains the ones found in PureScript, but there are others... some related to the compiler (`->`, `<=`, `=>`, etc.), some in other packages, etc.

**Comment by tippenein** [comment]
Yes and Yes! I think it would ultimately be the most beneficial to have a common-use example for each grouping of operators.

Something like:
```
   window                                   -- Window
     >>= windowToEventTarget   -- Window -> EventTarget
     >>> addEventListener popstate _ false      -- EventType -> EventListener -> Boolean -> EventTarget -> Eff Unit
```

Also, a console.log example is probably the most appropriate starting point for a "running" example

**Comment by tippenein** [comment]
Although, many of these examples will probably verge on _too much_ and should probably be linked to https://leanpub.com/purescript/read#leanpub-auto-functions-and-records or similar

**Comment by arecvlohe** [comment]
Good ideas @tippenein!

**Comment by arecvlohe** [comment]
So as far as the structure goes, are you going to get rid of the tables view and just have it be a top-down readme @joshburgess?

**Comment by joshburgess** [comment]
@arecvlohe No, I think the tables are useful for quick finding a symbol and referencing what package it's in or what it does.

I think we'll just have a few separate tables. I think the examples should be outside of the tables. Type signatures might be useful in the tables though. Not sure.

I want to keep the Prelude Infix Operator table separate from the rest that get added, since those are the most commonly used and what most people new to PureScript (if not coming from Haskell) will be confused about.

**Comment by joshburgess** [comment]
I'm going to go ahead and merge this as is, to get it out there, but  I'm going to change a few things about it. Feel free to keep tacking sections on, guys.

**Comment by joshburgess** [comment]
I added a new issue where we can keep the conversation going about adding examples, etc.... Do you two mind posting ideas there? https://github.com/joshburgess/purescript-cheat-sheet/issues/4

**Pull request merged**
